# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emaii',
            new_name='email',
        ),
    ]
